name: Selective Builds
description: Calculate the changed services comparing the contents of files to the previous run.
author: Meysam Azad
inputs:
  path:
    description: The directory to look for applications
    required: true
    default: "."
  redis-url:
    description: The host of the redis server
    required: true
  redis-token:
    description: The password of the redis server
    required: true
outputs:
  apps:
    description: A comma list of applications that need rebuild.
runs:
  using: "node20"
  main: dist/index.js
  post: dist/index.js
  post-if: success()
